#ifndef FBCP_COMMAND_H
#define FBCP_COMMAND_H

#include "fbcp.types.h"

namespace fbcp
{
  COMMAND Q_RAW_COMMAND = {"RAW", {"data"}};
  
  COMMAND Q_MODE_SELECT = {"MODE", {"mode"}};
  COMMAND A_MODE_ACCEPT = {"OK", {}};
  COMMAND A_MODE_DENY = {"DUNNO", {}};
  
  COMMAND Q_OPTION = {"OPT", {"option","value"}};
    PARAM OPTION_SET = {"ON"};
    PARAM OPTION_UNSET = {"OFF"};
  COMMAND A_OPTION_ACCEPT = {"OK", {}};
  COMMAND A_OPTION_DENY = {"DUNNO", {}};
  COMMAND A_ACCEPT = {"ON IT!", {}};
  COMMAND A_REFUSE = {"NOT NOW", {}};
  COMMAND A_ERROR = {"WHAT?", {}};
  COMMAND A_ALIKE = {"MAYBE", {"command"}};
  COMMAND Q_LIST = {"LIST", {}};
    PARAM LIST_OPT = {"OPT"};
    PARAM LIST_CMD = {"CMD"};
  
  COMMAND Q_HELP = {"EXPLAIN", {"command"}};
  COMMAND Q_LOG = {"LOG", {"data"}};
  COMMAND Q_SINGLE_PRESENTATION = {"I'M", {"serial"}};
  COMMAND Q_MULTI_PRESENTATION = {"WE'RE", {"serial","friend"}};
  
  COMMAND A_GRANT_ACCESS = {"WELCOME", {}};
  COMMAND A_DENY_ACCESS = {"BUSY", {}};
  
  COMMAND Q_HEARTBEAT = {"STILL THERE?", {}};
  COMMAND A_HEARTBEAT = {"YEP", {}};
  
  COMMAND Q_CLEAN = {"GOODBYE", {}};
  COMMAND A_CLEAN = {"BYE", {}};
  
  COMMAND A_REQUEST_PRESENTATION = {"WHO?", {}};
  
  COMMAND Q_CHANGE_NET = {"MOVE TO", {"net"}};
  COMMAND A_CHANGE_ACCEPT = {"OK", {}};
  COMMAND A_CHANGE_DENY = {"NO", {}};
  COMMAND Q_MOTOR_COMMAND = {"MOTOR", {"motor","direction"}};
    PARAM MOTOR_LEFT = {"ML"};
    PARAM MOTOR_RIGHT = {"MR"};
    PARAM MOTOR_BOTH = {"MLR"};
    PARAM DIRECTION_FORWARD = {"FW"};
    PARAM DIRECTION_BACKWARD = {"BW"};
    PARAM DIRECTION_STOP = {"STOP"};
  
  COMMAND Q_ROBOT_COMMAND = {"BOT", {"direction"}};
    /* ...other directions... */
    PARAM DIRECTION_FORWARD_LEFT = {"FL"};
    PARAM DIRECTION_FORWARD_RIGHT = {"FR"};
    PARAM DIRECTION_BACKWARD_LEFT = {"BL"};
    PARAM DIRECTION_BACKWARD_RIGHT = {"BR"};
    PARAM DIRECTION_LEFT = {"SL"};
    PARAM DIRECTION_RIGHT = {"SR"};
  
  COMMAND Q_HIT = {"OUCH", {}};
  
  COMMAND* Q_COMMANDS[] = {
    &Q_RAW_COMMAND,
    &Q_MODE_SELECT,
    &Q_OPTION,
    &Q_LIST,
    &Q_HELP,
    &Q_LOG,
    &Q_SINGLE_PRESENTATION,
    &Q_MULTI_PRESENTATION,
    &Q_HEARTBEAT,
    &Q_CLEAN,
    &Q_CHANGE_NET,
    &Q_MOTOR_COMMAND,
    &Q_ROBOT_COMMAND,
    &Q_HIT
  };
  COMMAND* A_COMMANDS[] = {
    &A_MODE_ACCEPT,
    &A_MODE_DENY,
    &A_OPTION_ACCEPT,
    &A_OPTION_DENY,
    &A_ACCEPT,
    &A_REFUSE,
    &A_ERROR,
    &A_ALIKE,
    &A_GRANT_ACCESS,
    &A_DENY_ACCESS,
    &A_HEARTBEAT,
    &A_CLEAN,
    &A_REQUEST_PRESENTATION,
    &A_CHANGE_ACCEPT,
    &A_CHANGE_DENY
  };
  PARAM* STD_PARAMS[] = {
    &OPTION_SET,
    &OPTION_UNSET,
    &LIST_OPT,
    &LIST_CMD,
    &MOTOR_LEFT,
    &MOTOR_RIGHT,
    &MOTOR_BOTH,
    &DIRECTION_FORWARD,
    &DIRECTION_BACKWARD,
    &DIRECTION_STOP,
    &DIRECTION_FORWARD_LEFT,
    &DIRECTION_FORWARD_RIGHT,
    &DIRECTION_BACKWARD_LEFT,
    &DIRECTION_BACKWARD_RIGHT,
    &DIRECTION_LEFT,
    &DIRECTION_RIGHT
  };

}

#endif // FBCP_COMMAND_H
