update: ../../FBCP/command_lists/fbcp.command.list
	cp ../../FBCP/command_lists/fbcp.command.list fbcp.command.list

../../FBCP/command_lists/fbcp.command.list:
	$(MAKE) -C ../../FBCP Makefile command_lists/fbcp.command.list
