#!/usr/bin/env python
import socket
from flipperbot import fbcp

fbcp.loadCommands()

sock = socket.socket()
serial = None
while serial is None:
  print("[R]obot/[C]ontroller/[O]ther: ", end="")
  c = input()
  if c == "R":
    d = 1
    print("Number [default={}]: ".format(d), end="")
    n = input()
    try:
      n = int(n)
    except:
      n = d
      print("Default used")
    serial = "FlipperBot-Robot-{:05d}".format(n)
  elif c == "C":
    d = 1
    print("Number [default={}]: ".format(d), end="")
    n = input()
    try:
      n = int(n)
    except:
      n = d
      print("Default used")
    serial = "FlipperBot-Robot-{:05d}".format(n)
  elif c == "O":
    print("Serial: ", end="")
    serial = input()
    if serial == "":
      serial = None
      print("Can't have void serial")
  else:
    print("Option not valid")

sock.connect(("192.168.1.1", 10000))
print("Connected to server")

cmd = fbcp.CommandLine()
cmd.command = fbcp.Command.Q_SINGLE_PRESENTATION
cmd.params['serial'] = serial

s = cmd.write()
sock.send(s.encode("UTF-8"))
print("Sent:", s)
msg = sock.recv(256).decode("UTF-8")
print("Received:", msg)
if not cmd.parse(msg):
  print("Couldn't understand message")
else if cmd.command == fbcp.Command.Q_DENY_ACCESS:
  print("Access denied")
else if cmd.command == fbcp.Command.Q_GRANT_ACCESS:
  print("Access granted")
  while cmd.command != fbcp.Command.Q_CLEAN and cmd.command != fbcp.Command.A_CLEAN:
    print("Command: ", end="")
    msg = input()
    if not msg.endswith("\n"):
      msg = msg + "\n"
    sock.send(msg.encode("UTF-8"))
    print("Sent:", msg)
    msg = sock.recv(256).decode("UTF-8")
    print("Received:", msg)
    if not cmd.parse(msg):
      print("Couldn't understand message")

sock.close()
