#!/usr/bin/env python
import sys

############
# DATASETS #
#   LIST   #
############
#  START   #
############
if len(sys.argv) > 1:
  datasets = sys.argv[1:]
else:
  f = open("datasets.list", "r")
  c = f.read()
  f.close()
  datasets = [
    record.split(";")[0]
    for record in c.split("\n")
    if not record.startswith("#")
  ]

datasets = [d for d in datasets if d != ""]
print("Datasets:")
print("\n".join(datasets))
############
#   END    #
############

for name in datasets:
  print("Starting analysis of dataset %s."%name)
  try:
    kff  = open(name+"/keyframes.dat", "r")
    content = kff.read()
    kff.close()
  except:
    print("Couldn't find keyframes for dataset %s"%name)
    continue
  try:
    keyframes = []
    lines = content.split("\n")
    for line in lines:
      line = line.strip()
      if line.startswith("#") or line=="":
        continue
      line = line.split(";")
      keyframes.append([int(line[0]), float(line[1])])
  except:
    print("Wrong keyframes file format for dataset %s"%name)
    continue
  out = open(name+"/annotated_keyframes.dat", "w")
  out.write("#Frame;Timestamp;Interval\n")
  old_time = None
  for (keyframe, new_time) in keyframes:
    if old_time is None:
      out.write("%d;%f;\n"%(keyframe,new_time))
    else:
      interval = new_time-old_time
      out.write("%d;%f;%f\n"%(keyframe,new_time,interval))
    old_time = new_time
  out.close()
  print("Done")
